<?php


namespace app\base;


use yii\web\Controller;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        $this->view->params['lastPage'] = \Yii::$app->session->get('lastPage');
        $this->view->params['admin'] = (\Yii::$app->user->can('adminActivity')) ? true : false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        \Yii::$app->session->set('lastPage',\Yii::$app->request->url);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

}