<?php


namespace app\base;


use yii\web\Controller;

class BaseController extends Controller
{
   /* public function beforeAction($action)
    {
        $action->lastPage = \Yii::$app->session->get('lastPage');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/
    public function afterAction($action, $result)
    {
        \Yii::$app->session->set('lastPage',\Yii::$app->request->url);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}