<?php


namespace app\controllers;


use app\base\BaseController;
use app\controllers\actions\admin\IndexAction;
use yii\web\HttpException;

class AdminController extends BaseController
{
     public function beforeAction($action)
     {
         if(!\Yii::$app->rbac->adminRbac()){
             throw new HttpException('401','Вы не обладаете правами администратора');
         }
         return parent::beforeAction($action); // TODO: Change the autogenerated stub
     }

    public function actions()
    {
        return [
            'index' => ['class' => IndexAction::class],
        ];
    }

}