<?php


namespace app\controllers;


use app\models\Users;
use yii\web\Controller;

class AuthController extends Controller
{
    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->auth = \Yii::$app->auth;
    }

    private $auth;

    public function beforeAction($action)
    {
        $this->view->params['lastPage'] = \Yii::$app->session->get('lastPage');
        $this->view->params['admin'] = (\Yii::$app->user->can('adminActivity')) ? true : false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        \Yii::$app->session->set('lastPage',\Yii::$app->request->url);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }



    public function actionSignUp(){
        $model = new Users();
        if(\Yii::$app->request->isPost){
            $model->load(\Yii::$app->request->post());
            if($this->auth->signUp($model)){
              //  $this->auth->log('Мы зарегились');
                return $this->redirect('/auth/sign-in');
            }
        }

        return $this->render('signup',['model'=>$model]);
    }

    public function actionSignIn(){
        $model = new Users();
        $adminka = false;
        if(\Yii::$app->request->isPost){
            $model->load(\Yii::$app->request->post());
            if($this->auth->signIn($model)){
               // \Yii::$app->auth->log('Мы вошли');
                return $this->redirect('/calendar/createCalendar');
            }
        }

        return $this->render('signin',['model'=>$model]);
    }
}